### ISSUE TITLE
1-deep-q-learning-simulated Run Issue

### ISSUE THREAD

**Issue by mgoyal0815** [FutureSharks/ml-finance#19]
Please explain the following code and possible solutions on your env.py as it does not run on my computer
```
        # observation space: give estimates in order to sample and build scaler
        data_max = self.price_data[self.environment_columns].max().tolist()
        data_range = [[0, i] for i in data_max]
        position_range = [[0, 2]]
        self.observation_space = spaces.MultiDiscrete([data_max] + data_range + position_range)
```
Please see the error below
```
    self.observation_space = spaces.MultiDiscrete([data_max] + data_range + position_range)

  File "C:\Users\Hello\anaconda3\lib\site-packages\gym\spaces\multi_discrete.py", line 30, in __init__
    assert (np.array(nvec) > 0).all(), 'nvec (counts) have to be positive'

AssertionError: nvec (counts) have to be positive
```

**Comment by FutureSharks** [comment]
@mgoyal0815 can you test with the requirements listed in here? https://github.com/FutureSharks/ml-finance/issues/14#issuecomment-666269887

**Comment by mgoyal0815** [comment]
@FutureSharks Thank you so much, this solves the issue. I am still trying to understand the logic of using data_max, data_range and position_range as observation space. I am really new to Q learning but shouldn't we be relying on just Price of the stock and RSI as our observation space? If you could explain your thinking process, it will help me a lot.

**Comment by FutureSharks** [comment]
> I am still trying to understand the logic of using data_max, data_range and position_range as observation space. I am really new to Q learning but shouldn't we be relying on just Price of the stock and RSI as our observation space? If you could explain your thinking process, it will help me a lot.

@mgoyal0815 I don't think you should read too much into these examples, most are not very good IMO.

You can see the example-1 is just a copy of example-0 but with simulated data to see if the agent/model can actually learn something that should be VERY learnable. But look at the references for example-0, it's this repo: https://github.com/ShuaiW/teach-machine-to-trade

I'm just copying that repo, implementing it in a jupyter notebook to understand it. I didn't write the agent, env or model.

Maybe look at [example-10](https://github.com/FutureSharks/ml-finance/blob/master/examples/10-deep-q-forex-variations/12h-EUR_USD_GBP_USD.ipynb), I rewrote the environment because the others are not good, choose the indicators and collected the price data. I'm very much not an expert in any of these topics though 🙂
